/*
 * generated by Xtext 2.9.1
 */
package org.example.domainmodel.idea.completion;

import org.eclipse.xtext.common.idea.completion.TerminalsCompletionContributor;
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public class AbstractDomainmodelCompletionContributor extends TerminalsCompletionContributor {
	public AbstractDomainmodelCompletionContributor(AbstractXtextLanguage lang) {
		super(lang);
	}
}
