/**
 * generated by Xtext 2.9.1
 */
package org.example.domainmodel.idea.highlighting;

import org.example.domainmodel.idea.highlighting.DomainmodelBaseColorSettingsPage;

@SuppressWarnings("all")
public class DomainmodelColorSettingsPage extends DomainmodelBaseColorSettingsPage {
}
