/*
 * generated by Xtext 2.9.1
 */
package org.example.domainmodel.idea.lang;

import com.intellij.psi.tree.IFileElementType;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.idea.lang.IElementTypeProvider;
import org.eclipse.xtext.psi.stubs.XtextFileElementType;
import org.eclipse.xtext.psi.stubs.XtextFileStub;
import org.eclipse.xtext.psi.tree.IGrammarAwareElementType;
import org.example.domainmodel.idea.lang.psi.impl.DomainmodelFileImpl;
import org.example.domainmodel.services.DomainmodelGrammarAccess;

public class DomainmodelElementTypeProvider implements IElementTypeProvider {

	public static final IFileElementType FILE_TYPE = new XtextFileElementType<XtextFileStub<DomainmodelFileImpl>>(DomainmodelLanguage.INSTANCE);

	private static final Map<EObject, IGrammarAwareElementType> GRAMMAR_ELEMENT_TYPE = new HashMap<EObject, IGrammarAwareElementType>();

	private static IGrammarAwareElementType associate(IGrammarAwareElementType grammarAwareElementType) {
		GRAMMAR_ELEMENT_TYPE.put(grammarAwareElementType.getGrammarElement(), grammarAwareElementType);
		return grammarAwareElementType;
	}

	private static final DomainmodelGrammarAccess GRAMMAR_ACCESS = DomainmodelLanguage.INSTANCE.getInstance(DomainmodelGrammarAccess.class);

	private static class DomainmodelFactory {
		public static IGrammarAwareElementType createDomainmodelElementType() {
			return new IGrammarAwareElementType("Domainmodel_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getDomainmodelRule());
		}
		public static IGrammarAwareElementType createDomainmodel_ElementsAssignmentElementType() {
			return new IGrammarAwareElementType("Domainmodel_ElementsAssignment_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getDomainmodelAccess().getElementsAssignment());
		}
		public static IGrammarAwareElementType createDomainmodel_ElementsAbstractElementParserRuleCall_0ElementType() {
			return new IGrammarAwareElementType("Domainmodel_ElementsAbstractElementParserRuleCall_0_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getDomainmodelAccess().getElementsAbstractElementParserRuleCall_0());
		}
	}

	public static final IGrammarAwareElementType Domainmodel_ELEMENT_TYPE = associate(DomainmodelFactory.createDomainmodelElementType());

	public static final IGrammarAwareElementType Domainmodel_ElementsAssignment_ELEMENT_TYPE = associate(DomainmodelFactory.createDomainmodel_ElementsAssignmentElementType());

	public static final IGrammarAwareElementType Domainmodel_ElementsAbstractElementParserRuleCall_0_ELEMENT_TYPE = associate(DomainmodelFactory.createDomainmodel_ElementsAbstractElementParserRuleCall_0ElementType());

	private static class PackageDeclarationFactory {
		public static IGrammarAwareElementType createPackageDeclarationElementType() {
			return new IGrammarAwareElementType("PackageDeclaration_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getPackageDeclarationRule());
		}
		public static IGrammarAwareElementType createPackageDeclaration_GroupElementType() {
			return new IGrammarAwareElementType("PackageDeclaration_Group_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getPackageDeclarationAccess().getGroup());
		}
		public static IGrammarAwareElementType createPackageDeclaration_PackageKeyword_0ElementType() {
			return new IGrammarAwareElementType("PackageDeclaration_PackageKeyword_0_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getPackageDeclarationAccess().getPackageKeyword_0());
		}
		public static IGrammarAwareElementType createPackageDeclaration_NameAssignment_1ElementType() {
			return new IGrammarAwareElementType("PackageDeclaration_NameAssignment_1_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getPackageDeclarationAccess().getNameAssignment_1());
		}
		public static IGrammarAwareElementType createPackageDeclaration_NameQualifiedNameParserRuleCall_1_0ElementType() {
			return new IGrammarAwareElementType("PackageDeclaration_NameQualifiedNameParserRuleCall_1_0_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getPackageDeclarationAccess().getNameQualifiedNameParserRuleCall_1_0());
		}
		public static IGrammarAwareElementType createPackageDeclaration_LeftCurlyBracketKeyword_2ElementType() {
			return new IGrammarAwareElementType("PackageDeclaration_LeftCurlyBracketKeyword_2_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getPackageDeclarationAccess().getLeftCurlyBracketKeyword_2());
		}
		public static IGrammarAwareElementType createPackageDeclaration_ElementsAssignment_3ElementType() {
			return new IGrammarAwareElementType("PackageDeclaration_ElementsAssignment_3_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getPackageDeclarationAccess().getElementsAssignment_3());
		}
		public static IGrammarAwareElementType createPackageDeclaration_ElementsAbstractElementParserRuleCall_3_0ElementType() {
			return new IGrammarAwareElementType("PackageDeclaration_ElementsAbstractElementParserRuleCall_3_0_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getPackageDeclarationAccess().getElementsAbstractElementParserRuleCall_3_0());
		}
		public static IGrammarAwareElementType createPackageDeclaration_RightCurlyBracketKeyword_4ElementType() {
			return new IGrammarAwareElementType("PackageDeclaration_RightCurlyBracketKeyword_4_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getPackageDeclarationAccess().getRightCurlyBracketKeyword_4());
		}
	}

	public static final IGrammarAwareElementType PackageDeclaration_ELEMENT_TYPE = associate(PackageDeclarationFactory.createPackageDeclarationElementType());

	public static final IGrammarAwareElementType PackageDeclaration_Group_ELEMENT_TYPE = associate(PackageDeclarationFactory.createPackageDeclaration_GroupElementType());

	public static final IGrammarAwareElementType PackageDeclaration_PackageKeyword_0_ELEMENT_TYPE = associate(PackageDeclarationFactory.createPackageDeclaration_PackageKeyword_0ElementType());

	public static final IGrammarAwareElementType PackageDeclaration_NameAssignment_1_ELEMENT_TYPE = associate(PackageDeclarationFactory.createPackageDeclaration_NameAssignment_1ElementType());

	public static final IGrammarAwareElementType PackageDeclaration_NameQualifiedNameParserRuleCall_1_0_ELEMENT_TYPE = associate(PackageDeclarationFactory.createPackageDeclaration_NameQualifiedNameParserRuleCall_1_0ElementType());

	public static final IGrammarAwareElementType PackageDeclaration_LeftCurlyBracketKeyword_2_ELEMENT_TYPE = associate(PackageDeclarationFactory.createPackageDeclaration_LeftCurlyBracketKeyword_2ElementType());

	public static final IGrammarAwareElementType PackageDeclaration_ElementsAssignment_3_ELEMENT_TYPE = associate(PackageDeclarationFactory.createPackageDeclaration_ElementsAssignment_3ElementType());

	public static final IGrammarAwareElementType PackageDeclaration_ElementsAbstractElementParserRuleCall_3_0_ELEMENT_TYPE = associate(PackageDeclarationFactory.createPackageDeclaration_ElementsAbstractElementParserRuleCall_3_0ElementType());

	public static final IGrammarAwareElementType PackageDeclaration_RightCurlyBracketKeyword_4_ELEMENT_TYPE = associate(PackageDeclarationFactory.createPackageDeclaration_RightCurlyBracketKeyword_4ElementType());

	private static class AbstractElementFactory {
		public static IGrammarAwareElementType createAbstractElementElementType() {
			return new IGrammarAwareElementType("AbstractElement_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getAbstractElementRule());
		}
		public static IGrammarAwareElementType createAbstractElement_AlternativesElementType() {
			return new IGrammarAwareElementType("AbstractElement_Alternatives_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getAbstractElementAccess().getAlternatives());
		}
		public static IGrammarAwareElementType createAbstractElement_PackageDeclarationParserRuleCall_0ElementType() {
			return new IGrammarAwareElementType("AbstractElement_PackageDeclarationParserRuleCall_0_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getAbstractElementAccess().getPackageDeclarationParserRuleCall_0());
		}
		public static IGrammarAwareElementType createAbstractElement_TypeParserRuleCall_1ElementType() {
			return new IGrammarAwareElementType("AbstractElement_TypeParserRuleCall_1_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getAbstractElementAccess().getTypeParserRuleCall_1());
		}
		public static IGrammarAwareElementType createAbstractElement_ImportParserRuleCall_2ElementType() {
			return new IGrammarAwareElementType("AbstractElement_ImportParserRuleCall_2_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getAbstractElementAccess().getImportParserRuleCall_2());
		}
	}

	public static final IGrammarAwareElementType AbstractElement_ELEMENT_TYPE = associate(AbstractElementFactory.createAbstractElementElementType());

	public static final IGrammarAwareElementType AbstractElement_Alternatives_ELEMENT_TYPE = associate(AbstractElementFactory.createAbstractElement_AlternativesElementType());

	public static final IGrammarAwareElementType AbstractElement_PackageDeclarationParserRuleCall_0_ELEMENT_TYPE = associate(AbstractElementFactory.createAbstractElement_PackageDeclarationParserRuleCall_0ElementType());

	public static final IGrammarAwareElementType AbstractElement_TypeParserRuleCall_1_ELEMENT_TYPE = associate(AbstractElementFactory.createAbstractElement_TypeParserRuleCall_1ElementType());

	public static final IGrammarAwareElementType AbstractElement_ImportParserRuleCall_2_ELEMENT_TYPE = associate(AbstractElementFactory.createAbstractElement_ImportParserRuleCall_2ElementType());

	private static class QualifiedNameFactory {
		public static IGrammarAwareElementType createQualifiedNameElementType() {
			return new IGrammarAwareElementType("QualifiedName_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getQualifiedNameRule());
		}
		public static IGrammarAwareElementType createQualifiedName_GroupElementType() {
			return new IGrammarAwareElementType("QualifiedName_Group_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getQualifiedNameAccess().getGroup());
		}
		public static IGrammarAwareElementType createQualifiedName_IDTerminalRuleCall_0ElementType() {
			return new IGrammarAwareElementType("QualifiedName_IDTerminalRuleCall_0_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getQualifiedNameAccess().getIDTerminalRuleCall_0());
		}
		public static IGrammarAwareElementType createQualifiedName_Group_1ElementType() {
			return new IGrammarAwareElementType("QualifiedName_Group_1_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getQualifiedNameAccess().getGroup_1());
		}
		public static IGrammarAwareElementType createQualifiedName_FullStopKeyword_1_0ElementType() {
			return new IGrammarAwareElementType("QualifiedName_FullStopKeyword_1_0_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getQualifiedNameAccess().getFullStopKeyword_1_0());
		}
		public static IGrammarAwareElementType createQualifiedName_IDTerminalRuleCall_1_1ElementType() {
			return new IGrammarAwareElementType("QualifiedName_IDTerminalRuleCall_1_1_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getQualifiedNameAccess().getIDTerminalRuleCall_1_1());
		}
	}

	public static final IGrammarAwareElementType QualifiedName_ELEMENT_TYPE = associate(QualifiedNameFactory.createQualifiedNameElementType());

	public static final IGrammarAwareElementType QualifiedName_Group_ELEMENT_TYPE = associate(QualifiedNameFactory.createQualifiedName_GroupElementType());

	public static final IGrammarAwareElementType QualifiedName_IDTerminalRuleCall_0_ELEMENT_TYPE = associate(QualifiedNameFactory.createQualifiedName_IDTerminalRuleCall_0ElementType());

	public static final IGrammarAwareElementType QualifiedName_Group_1_ELEMENT_TYPE = associate(QualifiedNameFactory.createQualifiedName_Group_1ElementType());

	public static final IGrammarAwareElementType QualifiedName_FullStopKeyword_1_0_ELEMENT_TYPE = associate(QualifiedNameFactory.createQualifiedName_FullStopKeyword_1_0ElementType());

	public static final IGrammarAwareElementType QualifiedName_IDTerminalRuleCall_1_1_ELEMENT_TYPE = associate(QualifiedNameFactory.createQualifiedName_IDTerminalRuleCall_1_1ElementType());

	private static class ImportFactory {
		public static IGrammarAwareElementType createImportElementType() {
			return new IGrammarAwareElementType("Import_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getImportRule());
		}
		public static IGrammarAwareElementType createImport_GroupElementType() {
			return new IGrammarAwareElementType("Import_Group_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getImportAccess().getGroup());
		}
		public static IGrammarAwareElementType createImport_ImportKeyword_0ElementType() {
			return new IGrammarAwareElementType("Import_ImportKeyword_0_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getImportAccess().getImportKeyword_0());
		}
		public static IGrammarAwareElementType createImport_ImportedNamespaceAssignment_1ElementType() {
			return new IGrammarAwareElementType("Import_ImportedNamespaceAssignment_1_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getImportAccess().getImportedNamespaceAssignment_1());
		}
		public static IGrammarAwareElementType createImport_ImportedNamespaceQualifiedNameWithWildcardParserRuleCall_1_0ElementType() {
			return new IGrammarAwareElementType("Import_ImportedNamespaceQualifiedNameWithWildcardParserRuleCall_1_0_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getImportAccess().getImportedNamespaceQualifiedNameWithWildcardParserRuleCall_1_0());
		}
	}

	public static final IGrammarAwareElementType Import_ELEMENT_TYPE = associate(ImportFactory.createImportElementType());

	public static final IGrammarAwareElementType Import_Group_ELEMENT_TYPE = associate(ImportFactory.createImport_GroupElementType());

	public static final IGrammarAwareElementType Import_ImportKeyword_0_ELEMENT_TYPE = associate(ImportFactory.createImport_ImportKeyword_0ElementType());

	public static final IGrammarAwareElementType Import_ImportedNamespaceAssignment_1_ELEMENT_TYPE = associate(ImportFactory.createImport_ImportedNamespaceAssignment_1ElementType());

	public static final IGrammarAwareElementType Import_ImportedNamespaceQualifiedNameWithWildcardParserRuleCall_1_0_ELEMENT_TYPE = associate(ImportFactory.createImport_ImportedNamespaceQualifiedNameWithWildcardParserRuleCall_1_0ElementType());

	private static class QualifiedNameWithWildcardFactory {
		public static IGrammarAwareElementType createQualifiedNameWithWildcardElementType() {
			return new IGrammarAwareElementType("QualifiedNameWithWildcard_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getQualifiedNameWithWildcardRule());
		}
		public static IGrammarAwareElementType createQualifiedNameWithWildcard_GroupElementType() {
			return new IGrammarAwareElementType("QualifiedNameWithWildcard_Group_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getQualifiedNameWithWildcardAccess().getGroup());
		}
		public static IGrammarAwareElementType createQualifiedNameWithWildcard_QualifiedNameParserRuleCall_0ElementType() {
			return new IGrammarAwareElementType("QualifiedNameWithWildcard_QualifiedNameParserRuleCall_0_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getQualifiedNameWithWildcardAccess().getQualifiedNameParserRuleCall_0());
		}
		public static IGrammarAwareElementType createQualifiedNameWithWildcard_FullStopAsteriskKeyword_1ElementType() {
			return new IGrammarAwareElementType("QualifiedNameWithWildcard_FullStopAsteriskKeyword_1_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getQualifiedNameWithWildcardAccess().getFullStopAsteriskKeyword_1());
		}
	}

	public static final IGrammarAwareElementType QualifiedNameWithWildcard_ELEMENT_TYPE = associate(QualifiedNameWithWildcardFactory.createQualifiedNameWithWildcardElementType());

	public static final IGrammarAwareElementType QualifiedNameWithWildcard_Group_ELEMENT_TYPE = associate(QualifiedNameWithWildcardFactory.createQualifiedNameWithWildcard_GroupElementType());

	public static final IGrammarAwareElementType QualifiedNameWithWildcard_QualifiedNameParserRuleCall_0_ELEMENT_TYPE = associate(QualifiedNameWithWildcardFactory.createQualifiedNameWithWildcard_QualifiedNameParserRuleCall_0ElementType());

	public static final IGrammarAwareElementType QualifiedNameWithWildcard_FullStopAsteriskKeyword_1_ELEMENT_TYPE = associate(QualifiedNameWithWildcardFactory.createQualifiedNameWithWildcard_FullStopAsteriskKeyword_1ElementType());

	private static class TypeFactory {
		public static IGrammarAwareElementType createTypeElementType() {
			return new IGrammarAwareElementType("Type_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getTypeRule());
		}
		public static IGrammarAwareElementType createType_AlternativesElementType() {
			return new IGrammarAwareElementType("Type_Alternatives_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getTypeAccess().getAlternatives());
		}
		public static IGrammarAwareElementType createType_DataTypeParserRuleCall_0ElementType() {
			return new IGrammarAwareElementType("Type_DataTypeParserRuleCall_0_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getTypeAccess().getDataTypeParserRuleCall_0());
		}
		public static IGrammarAwareElementType createType_EntityParserRuleCall_1ElementType() {
			return new IGrammarAwareElementType("Type_EntityParserRuleCall_1_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getTypeAccess().getEntityParserRuleCall_1());
		}
	}

	public static final IGrammarAwareElementType Type_ELEMENT_TYPE = associate(TypeFactory.createTypeElementType());

	public static final IGrammarAwareElementType Type_Alternatives_ELEMENT_TYPE = associate(TypeFactory.createType_AlternativesElementType());

	public static final IGrammarAwareElementType Type_DataTypeParserRuleCall_0_ELEMENT_TYPE = associate(TypeFactory.createType_DataTypeParserRuleCall_0ElementType());

	public static final IGrammarAwareElementType Type_EntityParserRuleCall_1_ELEMENT_TYPE = associate(TypeFactory.createType_EntityParserRuleCall_1ElementType());

	private static class DataTypeFactory {
		public static IGrammarAwareElementType createDataTypeElementType() {
			return new IGrammarAwareElementType("DataType_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getDataTypeRule());
		}
		public static IGrammarAwareElementType createDataType_GroupElementType() {
			return new IGrammarAwareElementType("DataType_Group_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getDataTypeAccess().getGroup());
		}
		public static IGrammarAwareElementType createDataType_DatatypeKeyword_0ElementType() {
			return new IGrammarAwareElementType("DataType_DatatypeKeyword_0_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getDataTypeAccess().getDatatypeKeyword_0());
		}
		public static IGrammarAwareElementType createDataType_NameAssignment_1ElementType() {
			return new IGrammarAwareElementType("DataType_NameAssignment_1_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getDataTypeAccess().getNameAssignment_1());
		}
		public static IGrammarAwareElementType createDataType_NameIDTerminalRuleCall_1_0ElementType() {
			return new IGrammarAwareElementType("DataType_NameIDTerminalRuleCall_1_0_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getDataTypeAccess().getNameIDTerminalRuleCall_1_0());
		}
	}

	public static final IGrammarAwareElementType DataType_ELEMENT_TYPE = associate(DataTypeFactory.createDataTypeElementType());

	public static final IGrammarAwareElementType DataType_Group_ELEMENT_TYPE = associate(DataTypeFactory.createDataType_GroupElementType());

	public static final IGrammarAwareElementType DataType_DatatypeKeyword_0_ELEMENT_TYPE = associate(DataTypeFactory.createDataType_DatatypeKeyword_0ElementType());

	public static final IGrammarAwareElementType DataType_NameAssignment_1_ELEMENT_TYPE = associate(DataTypeFactory.createDataType_NameAssignment_1ElementType());

	public static final IGrammarAwareElementType DataType_NameIDTerminalRuleCall_1_0_ELEMENT_TYPE = associate(DataTypeFactory.createDataType_NameIDTerminalRuleCall_1_0ElementType());

	private static class EntityFactory {
		public static IGrammarAwareElementType createEntityElementType() {
			return new IGrammarAwareElementType("Entity_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getEntityRule());
		}
		public static IGrammarAwareElementType createEntity_GroupElementType() {
			return new IGrammarAwareElementType("Entity_Group_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getEntityAccess().getGroup());
		}
		public static IGrammarAwareElementType createEntity_EntityKeyword_0ElementType() {
			return new IGrammarAwareElementType("Entity_EntityKeyword_0_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getEntityAccess().getEntityKeyword_0());
		}
		public static IGrammarAwareElementType createEntity_NameAssignment_1ElementType() {
			return new IGrammarAwareElementType("Entity_NameAssignment_1_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getEntityAccess().getNameAssignment_1());
		}
		public static IGrammarAwareElementType createEntity_NameIDTerminalRuleCall_1_0ElementType() {
			return new IGrammarAwareElementType("Entity_NameIDTerminalRuleCall_1_0_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getEntityAccess().getNameIDTerminalRuleCall_1_0());
		}
		public static IGrammarAwareElementType createEntity_Group_2ElementType() {
			return new IGrammarAwareElementType("Entity_Group_2_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getEntityAccess().getGroup_2());
		}
		public static IGrammarAwareElementType createEntity_ExtendsKeyword_2_0ElementType() {
			return new IGrammarAwareElementType("Entity_ExtendsKeyword_2_0_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getEntityAccess().getExtendsKeyword_2_0());
		}
		public static IGrammarAwareElementType createEntity_SuperTypeAssignment_2_1ElementType() {
			return new IGrammarAwareElementType("Entity_SuperTypeAssignment_2_1_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getEntityAccess().getSuperTypeAssignment_2_1());
		}
		public static IGrammarAwareElementType createEntity_SuperTypeEntityCrossReference_2_1_0ElementType() {
			return new IGrammarAwareElementType("Entity_SuperTypeEntityCrossReference_2_1_0_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getEntityAccess().getSuperTypeEntityCrossReference_2_1_0());
		}
		public static IGrammarAwareElementType createEntity_SuperTypeEntityQualifiedNameParserRuleCall_2_1_0_1ElementType() {
			return new IGrammarAwareElementType("Entity_SuperTypeEntityQualifiedNameParserRuleCall_2_1_0_1_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getEntityAccess().getSuperTypeEntityQualifiedNameParserRuleCall_2_1_0_1());
		}
		public static IGrammarAwareElementType createEntity_LeftCurlyBracketKeyword_3ElementType() {
			return new IGrammarAwareElementType("Entity_LeftCurlyBracketKeyword_3_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getEntityAccess().getLeftCurlyBracketKeyword_3());
		}
		public static IGrammarAwareElementType createEntity_FeaturesAssignment_4ElementType() {
			return new IGrammarAwareElementType("Entity_FeaturesAssignment_4_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getEntityAccess().getFeaturesAssignment_4());
		}
		public static IGrammarAwareElementType createEntity_FeaturesFeatureParserRuleCall_4_0ElementType() {
			return new IGrammarAwareElementType("Entity_FeaturesFeatureParserRuleCall_4_0_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getEntityAccess().getFeaturesFeatureParserRuleCall_4_0());
		}
		public static IGrammarAwareElementType createEntity_RightCurlyBracketKeyword_5ElementType() {
			return new IGrammarAwareElementType("Entity_RightCurlyBracketKeyword_5_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getEntityAccess().getRightCurlyBracketKeyword_5());
		}
	}

	public static final IGrammarAwareElementType Entity_ELEMENT_TYPE = associate(EntityFactory.createEntityElementType());

	public static final IGrammarAwareElementType Entity_Group_ELEMENT_TYPE = associate(EntityFactory.createEntity_GroupElementType());

	public static final IGrammarAwareElementType Entity_EntityKeyword_0_ELEMENT_TYPE = associate(EntityFactory.createEntity_EntityKeyword_0ElementType());

	public static final IGrammarAwareElementType Entity_NameAssignment_1_ELEMENT_TYPE = associate(EntityFactory.createEntity_NameAssignment_1ElementType());

	public static final IGrammarAwareElementType Entity_NameIDTerminalRuleCall_1_0_ELEMENT_TYPE = associate(EntityFactory.createEntity_NameIDTerminalRuleCall_1_0ElementType());

	public static final IGrammarAwareElementType Entity_Group_2_ELEMENT_TYPE = associate(EntityFactory.createEntity_Group_2ElementType());

	public static final IGrammarAwareElementType Entity_ExtendsKeyword_2_0_ELEMENT_TYPE = associate(EntityFactory.createEntity_ExtendsKeyword_2_0ElementType());

	public static final IGrammarAwareElementType Entity_SuperTypeAssignment_2_1_ELEMENT_TYPE = associate(EntityFactory.createEntity_SuperTypeAssignment_2_1ElementType());

	public static final IGrammarAwareElementType Entity_SuperTypeEntityCrossReference_2_1_0_ELEMENT_TYPE = associate(EntityFactory.createEntity_SuperTypeEntityCrossReference_2_1_0ElementType());

	public static final IGrammarAwareElementType Entity_SuperTypeEntityQualifiedNameParserRuleCall_2_1_0_1_ELEMENT_TYPE = associate(EntityFactory.createEntity_SuperTypeEntityQualifiedNameParserRuleCall_2_1_0_1ElementType());

	public static final IGrammarAwareElementType Entity_LeftCurlyBracketKeyword_3_ELEMENT_TYPE = associate(EntityFactory.createEntity_LeftCurlyBracketKeyword_3ElementType());

	public static final IGrammarAwareElementType Entity_FeaturesAssignment_4_ELEMENT_TYPE = associate(EntityFactory.createEntity_FeaturesAssignment_4ElementType());

	public static final IGrammarAwareElementType Entity_FeaturesFeatureParserRuleCall_4_0_ELEMENT_TYPE = associate(EntityFactory.createEntity_FeaturesFeatureParserRuleCall_4_0ElementType());

	public static final IGrammarAwareElementType Entity_RightCurlyBracketKeyword_5_ELEMENT_TYPE = associate(EntityFactory.createEntity_RightCurlyBracketKeyword_5ElementType());

	private static class FeatureFactory {
		public static IGrammarAwareElementType createFeatureElementType() {
			return new IGrammarAwareElementType("Feature_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getFeatureRule());
		}
		public static IGrammarAwareElementType createFeature_GroupElementType() {
			return new IGrammarAwareElementType("Feature_Group_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getFeatureAccess().getGroup());
		}
		public static IGrammarAwareElementType createFeature_ManyAssignment_0ElementType() {
			return new IGrammarAwareElementType("Feature_ManyAssignment_0_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getFeatureAccess().getManyAssignment_0());
		}
		public static IGrammarAwareElementType createFeature_ManyManyKeyword_0_0ElementType() {
			return new IGrammarAwareElementType("Feature_ManyManyKeyword_0_0_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getFeatureAccess().getManyManyKeyword_0_0());
		}
		public static IGrammarAwareElementType createFeature_NameAssignment_1ElementType() {
			return new IGrammarAwareElementType("Feature_NameAssignment_1_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getFeatureAccess().getNameAssignment_1());
		}
		public static IGrammarAwareElementType createFeature_NameIDTerminalRuleCall_1_0ElementType() {
			return new IGrammarAwareElementType("Feature_NameIDTerminalRuleCall_1_0_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getFeatureAccess().getNameIDTerminalRuleCall_1_0());
		}
		public static IGrammarAwareElementType createFeature_ColonKeyword_2ElementType() {
			return new IGrammarAwareElementType("Feature_ColonKeyword_2_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getFeatureAccess().getColonKeyword_2());
		}
		public static IGrammarAwareElementType createFeature_TypeAssignment_3ElementType() {
			return new IGrammarAwareElementType("Feature_TypeAssignment_3_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getFeatureAccess().getTypeAssignment_3());
		}
		public static IGrammarAwareElementType createFeature_TypeTypeCrossReference_3_0ElementType() {
			return new IGrammarAwareElementType("Feature_TypeTypeCrossReference_3_0_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getFeatureAccess().getTypeTypeCrossReference_3_0());
		}
		public static IGrammarAwareElementType createFeature_TypeTypeQualifiedNameParserRuleCall_3_0_1ElementType() {
			return new IGrammarAwareElementType("Feature_TypeTypeQualifiedNameParserRuleCall_3_0_1_ELEMENT_TYPE", DomainmodelLanguage.INSTANCE, GRAMMAR_ACCESS.getFeatureAccess().getTypeTypeQualifiedNameParserRuleCall_3_0_1());
		}
	}

	public static final IGrammarAwareElementType Feature_ELEMENT_TYPE = associate(FeatureFactory.createFeatureElementType());

	public static final IGrammarAwareElementType Feature_Group_ELEMENT_TYPE = associate(FeatureFactory.createFeature_GroupElementType());

	public static final IGrammarAwareElementType Feature_ManyAssignment_0_ELEMENT_TYPE = associate(FeatureFactory.createFeature_ManyAssignment_0ElementType());

	public static final IGrammarAwareElementType Feature_ManyManyKeyword_0_0_ELEMENT_TYPE = associate(FeatureFactory.createFeature_ManyManyKeyword_0_0ElementType());

	public static final IGrammarAwareElementType Feature_NameAssignment_1_ELEMENT_TYPE = associate(FeatureFactory.createFeature_NameAssignment_1ElementType());

	public static final IGrammarAwareElementType Feature_NameIDTerminalRuleCall_1_0_ELEMENT_TYPE = associate(FeatureFactory.createFeature_NameIDTerminalRuleCall_1_0ElementType());

	public static final IGrammarAwareElementType Feature_ColonKeyword_2_ELEMENT_TYPE = associate(FeatureFactory.createFeature_ColonKeyword_2ElementType());

	public static final IGrammarAwareElementType Feature_TypeAssignment_3_ELEMENT_TYPE = associate(FeatureFactory.createFeature_TypeAssignment_3ElementType());

	public static final IGrammarAwareElementType Feature_TypeTypeCrossReference_3_0_ELEMENT_TYPE = associate(FeatureFactory.createFeature_TypeTypeCrossReference_3_0ElementType());

	public static final IGrammarAwareElementType Feature_TypeTypeQualifiedNameParserRuleCall_3_0_1_ELEMENT_TYPE = associate(FeatureFactory.createFeature_TypeTypeQualifiedNameParserRuleCall_3_0_1ElementType());

	@Override
	public IFileElementType getFileType() {
		return FILE_TYPE;
	}

	@Override
	public IGrammarAwareElementType findElementType(EObject grammarElement) {
		return GRAMMAR_ELEMENT_TYPE.get(grammarElement);
	}
	
	public IGrammarAwareElementType getDomainmodelElementType() {
		return Domainmodel_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDomainmodel_ElementsAssignmentElementType() {
		return Domainmodel_ElementsAssignment_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDomainmodel_ElementsAbstractElementParserRuleCall_0ElementType() {
		return Domainmodel_ElementsAbstractElementParserRuleCall_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPackageDeclarationElementType() {
		return PackageDeclaration_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPackageDeclaration_GroupElementType() {
		return PackageDeclaration_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPackageDeclaration_PackageKeyword_0ElementType() {
		return PackageDeclaration_PackageKeyword_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPackageDeclaration_NameAssignment_1ElementType() {
		return PackageDeclaration_NameAssignment_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPackageDeclaration_NameQualifiedNameParserRuleCall_1_0ElementType() {
		return PackageDeclaration_NameQualifiedNameParserRuleCall_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPackageDeclaration_LeftCurlyBracketKeyword_2ElementType() {
		return PackageDeclaration_LeftCurlyBracketKeyword_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPackageDeclaration_ElementsAssignment_3ElementType() {
		return PackageDeclaration_ElementsAssignment_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPackageDeclaration_ElementsAbstractElementParserRuleCall_3_0ElementType() {
		return PackageDeclaration_ElementsAbstractElementParserRuleCall_3_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPackageDeclaration_RightCurlyBracketKeyword_4ElementType() {
		return PackageDeclaration_RightCurlyBracketKeyword_4_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAbstractElementElementType() {
		return AbstractElement_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAbstractElement_AlternativesElementType() {
		return AbstractElement_Alternatives_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAbstractElement_PackageDeclarationParserRuleCall_0ElementType() {
		return AbstractElement_PackageDeclarationParserRuleCall_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAbstractElement_TypeParserRuleCall_1ElementType() {
		return AbstractElement_TypeParserRuleCall_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAbstractElement_ImportParserRuleCall_2ElementType() {
		return AbstractElement_ImportParserRuleCall_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getQualifiedNameElementType() {
		return QualifiedName_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getQualifiedName_GroupElementType() {
		return QualifiedName_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getQualifiedName_IDTerminalRuleCall_0ElementType() {
		return QualifiedName_IDTerminalRuleCall_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getQualifiedName_Group_1ElementType() {
		return QualifiedName_Group_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getQualifiedName_FullStopKeyword_1_0ElementType() {
		return QualifiedName_FullStopKeyword_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getQualifiedName_IDTerminalRuleCall_1_1ElementType() {
		return QualifiedName_IDTerminalRuleCall_1_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getImportElementType() {
		return Import_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getImport_GroupElementType() {
		return Import_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getImport_ImportKeyword_0ElementType() {
		return Import_ImportKeyword_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getImport_ImportedNamespaceAssignment_1ElementType() {
		return Import_ImportedNamespaceAssignment_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getImport_ImportedNamespaceQualifiedNameWithWildcardParserRuleCall_1_0ElementType() {
		return Import_ImportedNamespaceQualifiedNameWithWildcardParserRuleCall_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getQualifiedNameWithWildcardElementType() {
		return QualifiedNameWithWildcard_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getQualifiedNameWithWildcard_GroupElementType() {
		return QualifiedNameWithWildcard_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getQualifiedNameWithWildcard_QualifiedNameParserRuleCall_0ElementType() {
		return QualifiedNameWithWildcard_QualifiedNameParserRuleCall_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getQualifiedNameWithWildcard_FullStopAsteriskKeyword_1ElementType() {
		return QualifiedNameWithWildcard_FullStopAsteriskKeyword_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getTypeElementType() {
		return Type_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getType_AlternativesElementType() {
		return Type_Alternatives_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getType_DataTypeParserRuleCall_0ElementType() {
		return Type_DataTypeParserRuleCall_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getType_EntityParserRuleCall_1ElementType() {
		return Type_EntityParserRuleCall_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDataTypeElementType() {
		return DataType_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDataType_GroupElementType() {
		return DataType_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDataType_DatatypeKeyword_0ElementType() {
		return DataType_DatatypeKeyword_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDataType_NameAssignment_1ElementType() {
		return DataType_NameAssignment_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDataType_NameIDTerminalRuleCall_1_0ElementType() {
		return DataType_NameIDTerminalRuleCall_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getEntityElementType() {
		return Entity_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getEntity_GroupElementType() {
		return Entity_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getEntity_EntityKeyword_0ElementType() {
		return Entity_EntityKeyword_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getEntity_NameAssignment_1ElementType() {
		return Entity_NameAssignment_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getEntity_NameIDTerminalRuleCall_1_0ElementType() {
		return Entity_NameIDTerminalRuleCall_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getEntity_Group_2ElementType() {
		return Entity_Group_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getEntity_ExtendsKeyword_2_0ElementType() {
		return Entity_ExtendsKeyword_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getEntity_SuperTypeAssignment_2_1ElementType() {
		return Entity_SuperTypeAssignment_2_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getEntity_SuperTypeEntityCrossReference_2_1_0ElementType() {
		return Entity_SuperTypeEntityCrossReference_2_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getEntity_SuperTypeEntityQualifiedNameParserRuleCall_2_1_0_1ElementType() {
		return Entity_SuperTypeEntityQualifiedNameParserRuleCall_2_1_0_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getEntity_LeftCurlyBracketKeyword_3ElementType() {
		return Entity_LeftCurlyBracketKeyword_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getEntity_FeaturesAssignment_4ElementType() {
		return Entity_FeaturesAssignment_4_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getEntity_FeaturesFeatureParserRuleCall_4_0ElementType() {
		return Entity_FeaturesFeatureParserRuleCall_4_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getEntity_RightCurlyBracketKeyword_5ElementType() {
		return Entity_RightCurlyBracketKeyword_5_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFeatureElementType() {
		return Feature_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFeature_GroupElementType() {
		return Feature_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFeature_ManyAssignment_0ElementType() {
		return Feature_ManyAssignment_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFeature_ManyManyKeyword_0_0ElementType() {
		return Feature_ManyManyKeyword_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFeature_NameAssignment_1ElementType() {
		return Feature_NameAssignment_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFeature_NameIDTerminalRuleCall_1_0ElementType() {
		return Feature_NameIDTerminalRuleCall_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFeature_ColonKeyword_2ElementType() {
		return Feature_ColonKeyword_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFeature_TypeAssignment_3ElementType() {
		return Feature_TypeAssignment_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFeature_TypeTypeCrossReference_3_0ElementType() {
		return Feature_TypeTypeCrossReference_3_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFeature_TypeTypeQualifiedNameParserRuleCall_3_0_1ElementType() {
		return Feature_TypeTypeQualifiedNameParserRuleCall_3_0_1_ELEMENT_TYPE;
	}

}
