/*
 * generated by Xtext 2.9.1
 */
package org.example.domainmodel.idea.lang;

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public final class DomainmodelLanguage extends AbstractXtextLanguage {

	public static final DomainmodelLanguage INSTANCE = new DomainmodelLanguage();

	private DomainmodelLanguage() {
		super("org.example.domainmodel.Domainmodel");
	}

}
