/**
 * generated by Xtext 2.9.1
 */
package org.example.domainmodel.idea.lang;

import org.example.domainmodel.idea.lang.AbstractDomainmodelFileType;
import org.example.domainmodel.idea.lang.DomainmodelLanguage;

@SuppressWarnings("all")
public class DomainmodelFileType extends AbstractDomainmodelFileType {
  public final static DomainmodelFileType INSTANCE = new DomainmodelFileType();
  
  public DomainmodelFileType() {
    super(DomainmodelLanguage.INSTANCE);
  }
}
