/*
 * generated by Xtext 2.9.1
 */
package org.example.domainmodel.idea.highlighting;

import org.eclipse.xtext.idea.highlighting.AbstractColorSettingsPage;
import org.example.domainmodel.idea.lang.DomainmodelLanguage;

public class DomainmodelBaseColorSettingsPage extends AbstractColorSettingsPage {
	
	public DomainmodelBaseColorSettingsPage() {
		DomainmodelLanguage.INSTANCE.injectMembers(this);
	}

	@Override
	public String getDisplayName() {
		return DomainmodelLanguage.INSTANCE.getDisplayName();
	}
}
