/**
 * generated by Xtext 2.9.1
 */
package org.example.domainmodel.idea;

import org.example.domainmodel.idea.AbstractDomainmodelIdeaModule;

/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
@SuppressWarnings("all")
public class DomainmodelIdeaModule extends AbstractDomainmodelIdeaModule {
}
