/**
 * generated by Xtext 2.9.1
 */
package org.example.domainmodel.idea;

import com.google.inject.Injector;

@SuppressWarnings("all")
public class DomainmodelStandaloneSetupIdea /* implements DomainmodelStandaloneSetupGenerated  */{
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from DomainmodelRuntimeModule to Module");
  }
}
