/**
 * generated by Xtext 2.9.1
 */
package org.example.domainmodel;

import org.example.domainmodel.AbstractDomainmodelRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class DomainmodelRuntimeModule extends AbstractDomainmodelRuntimeModule {
}
