/**
 * generated by Xtext 2.9.1
 */
package org.example.domainmodel;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class DomainmodelStandaloneSetup /* implements DomainmodelStandaloneSetupGenerated  */{
  public static void doSetup() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method createInjectorAndDoEMFRegistration() is undefined for the type DomainmodelStandaloneSetup");
  }
}
