/**
 * generated by Xtext 2.9.1
 */
package org.example.domainmodel.idea.completion;

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;
import org.example.domainmodel.idea.completion.AbstractDomainmodelCompletionContributor;
import org.example.domainmodel.idea.lang.DomainmodelLanguage;

@SuppressWarnings("all")
public class DomainmodelCompletionContributor extends AbstractDomainmodelCompletionContributor {
  public DomainmodelCompletionContributor() {
    this(DomainmodelLanguage.INSTANCE);
  }
  
  public DomainmodelCompletionContributor(final AbstractXtextLanguage lang) {
    super(lang);
  }
}
