/*
 * generated by Xtext 2.9.1
 */
package org.example.domainmodel.idea.facet;

import com.intellij.facet.Facet;
import com.intellij.facet.FacetTypeId;
import org.eclipse.xtext.idea.facet.AbstractFacetType;
import org.example.domainmodel.idea.lang.DomainmodelLanguage;

public class DomainmodelFacetType extends AbstractFacetType<DomainmodelFacetConfiguration> {

	public static final FacetTypeId<Facet<DomainmodelFacetConfiguration>> TYPEID = new FacetTypeId<Facet<DomainmodelFacetConfiguration>>("org.example.domainmodel.Domainmodel");

	public DomainmodelFacetType() {
		super(TYPEID, "org.example.domainmodel.Domainmodel", "Domainmodel");
		DomainmodelLanguage.INSTANCE.injectMembers(this);
	}
}
