/**
 * generated by Xtext 2.9.1
 */
package org.example.domainmodel.validation;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DomainmodelValidator /* implements AbstractDomainmodelValidator  */{
}
