/**
 * generated by Xtext 2.9.1
 */
package org.example.domainmodel.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.google.inject.Module;
import com.google.inject.Provider;
import com.google.inject.util.Modules;
import java.util.concurrent.ExecutorService;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.example.domainmodel.DomainmodelRuntimeModule;
import org.example.domainmodel.DomainmodelStandaloneSetup;
import org.example.domainmodel.web.DomainmodelWebModule;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class DomainmodelWebSetup extends DomainmodelStandaloneSetup {
  private final Provider<ExecutorService> executorServiceProvider;
  
  @Override
  public Injector createInjector() {
    final DomainmodelRuntimeModule runtimeModule = new DomainmodelRuntimeModule();
    final DomainmodelWebModule webModule = new DomainmodelWebModule(this.executorServiceProvider);
    Modules.OverriddenModuleBuilder _override = Modules.override(runtimeModule);
    Module _with = _override.with(webModule);
    return Guice.createInjector(_with);
  }
  
  public DomainmodelWebSetup(final Provider<ExecutorService> executorServiceProvider) {
    super();
    this.executorServiceProvider = executorServiceProvider;
  }
}
