/**
 * generated by Xtext 2.9.1
 */
package org.example.domainmodel.web;

import com.google.inject.Provider;
import java.util.concurrent.ExecutorService;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.example.domainmodel.web.AbstractDomainmodelWebModule;

/**
 * Use this class to register additional components to be used within the web application.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class DomainmodelWebModule extends AbstractDomainmodelWebModule {
  public DomainmodelWebModule(final Provider<ExecutorService> executorServiceProvider) {
    super(executorServiceProvider);
  }
}
